os: Visual Studio 2015

platform:
  - x64

branches:
  only:
  - release

version: '{build}-{branch}'

cache:
  - 'node_modules'
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - cmd: git config --global core.autocrlf input

install:
  - cmd: echo 🔧 Installing tools
  - ps: Install-Product node 7.7.2

before_build:
  - cmd: echo 📥 Installing dependencies
  - cmd: npm install

build_script:
  - cmd: echo 📦 Building artifacts
  - cmd: npm run-script build

deploy_script:
  - cmd: echo 📮 Deploying artifacts
  - cmd: npm run-script deploy:github

artifacts:
  - path: build\output\win\*.exe

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/f29f98b58ec67b5f0f59
    method: GET
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

test: off
