os:
  - osx

sudo: false

language:
  - ruby

rvm:
  - 2.2.1

cache:
  bundler: true
  directories:
    - node_modules
    - cache
    - $HOME/.electron
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.gem
    - $HOME/travis-cache
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Cellar

before_install:
  - brew update
  - brew install wine
  - wine --version
  - brew install makensis
  - makensis -VERSION
  - brew install mono
  - mono --version
  - gem install fpm
  - fpm --version
  - brew install fakeroot
  - fakeroot -v
  - brew install dpkg
  - dpkg --version

install:
  - export PATH=~/bin:$PATH
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | NVM_DIR=$HOME/.nvm sh
  - source $HOME/.nvm/nvm.sh
  - command -v nvm
  - nvm ls-remote
  - nvm install 6.2.2
  - nvm use 6.2.2

before_script:
  - npm prune
  - npm install

script:
  - npm run pack --verbose
  - npm run publish  --verbose

notifications:
  email:
    - sidneys.github.io@outlook.com
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/b3225bd958673b2d9f82
    on_success: always
    on_failure: always
    on_start: always
