git:
  depth: 10

branches:
  only:
    - master

os:
  - osx

osx_image: xcode8
language: objective-c
compiler: clang
sudo: false

env:
  global:
    - SIGN_DARWIN_KEYCHAIN_NAME=travis.keychain
    - SIGN_DARWIN_KEYCHAIN_PASSWORD=travis

before_install:
- brew install wine --HEAD --with-libgsm --with-samba
- brew install mono

install:
  - export PATH=~/bin:$PATH
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install 6.2.2
  - nvm use 6.2.2
  - npm install
  - export npm_config_target=`node -pe "require('package.json').build.electron.substring(1)"`
  - cd src && HOME=~/.electron-gyp npm_config_disturl="https://atom.io/download/atom-shell" npm_config_arch="x64" npm_config_runtime="electron" npm install && cd ..

script:
  - npm run-script pack --verbose

cache:
  directories:
    - node_modules
    - src/node_modules
    - cache

notifications:
  email: false
  webhooks:
    - https://webhooks.gitter.im/e/b3225bd958673b2d9f82
