os:
  - osx

sudo: false

language:
  - ruby

rvm:
  - 2.2.0

cache:
  bundler: true
  directories:
    - node_modules
    - cache
    - $HOME/.electron
    - $HOME/.npm
    - $HOME/.gem
    - $HOME/travis-cache
    - $HOME/Library/Caches/Homebrew

before_install:
  - brew update
  - brew install wine
  - wine --version
  - brew install makensis
  - makensis -VERSION
  - brew install mono
  - mono --version
  - gem install fpm
  - fpm --version
  - brew install fakeroot
  - fakeroot -v
  - brew install dpkg
  - dpkg --version

install:
  - export PATH=~/bin:$PATH
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install 6.2.2
  - nvm use 6.2.2

before_script:
  - npm prune
  - npm install

script:
  - npm run pack --verbose

notifications:
  email: false
  webhooks:
    - https://webhooks.gitter.im/e/b3225bd958673b2d9f82
