os:
  - osx

sudo: false

language:
  - ruby

rvm:
  - 2.2.0

cache:
  directories:
    - node_modules
    - cache
    - $HOME/.electron
    - $HOME/.npm

before_install:
  - brew update

install:
  - brew install wine
  - wine --version
  - brew install makensis
  - brew install mono
  - gem install fpm
  - fpm --version

before_script:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install 6.2.2
  - nvm use 6.2.2
  - npm prune --verbose
  - npm install --verbose

script:
  - npm run pack --verbose

notifications:
  email: false
  webhooks:
    - https://webhooks.gitter.im/e/b3225bd958673b2d9f82
